"""Default (non-secret) configuration values used by BaseSettings."""
from __future__ import annotations

from zoneinfo import ZoneInfo

DEFAULT_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf"
DEFAULT_TEST_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf_test"
DEFAULT_API_BASE_URL = "http://localhost:8000/api/v1"
DEFAULT_REPLY_PROVIDER = "openai"
DEFAULT_REPLY_MODEL = "gpt-4o-mini"
DEFAULT_REPLY_TEMPERATURE = 0.2
DEFAULT_REPLY_MAX_OUTPUT_TOKENS = None
DEFAULT_REPLY_MAX_CONTEXT_CHARS = 20000

DEFAULT_MESSAGE_HISTORY_SIZE = 20
DEFAULT_TZ = ZoneInfo("Asia/Taipei")
DEFAULT_DAYS = 30
DEFAULT_SEARCH_DAYS = 7
EXPANDED_SEARCH_DAYS = 14
JSON_SENTINEL = "#"
NOT_SPECIFIED = "NOT_SPECIFIED"
GLOBAL_ERROR_THRESHOLD=3
CONSECUTIVE_ERROR_THRESHOLD=2
DEFAULT_OPENING_TIME = "09:00"
DEFAULT_CLOSING_TIME = "17:00"
DEFAULT_APPOINTMENT_DURATION_MIN = 30
DAY_START_HOUR = 9
DAY_START_MINUTE = 0

AFTERNOON_HOUR = 12
AFTERNOON_MINUTE = 0
TOTAL_DELAY_KEY = "total_delay_s"
AI_DELAY_KEY = "ai_delay_s"
NON_AI_DELAY_KEY = "non_ai_delay_s"
INPUT_TOKENS_KEY = "input_tokens"
OUTPUT_TOKENS_KEY = "output_tokens"
TOTAL_TOKENS_KEY = "total_tokens"
FIRST_TOKEN_DELAY_KEY = "first_token_delay_s"
DELAY_KEYS = (TOTAL_DELAY_KEY, AI_DELAY_KEY, NON_AI_DELAY_KEY)
TOKEN_KEYS = (INPUT_TOKENS_KEY, OUTPUT_TOKENS_KEY, TOTAL_TOKENS_KEY)
NODE_TIMING_KEYS = DELAY_KEYS + TOKEN_KEYS
