"""Default (non-secret) configuration values used by BaseSettings."""
from __future__ import annotations

from zoneinfo import ZoneInfo

DEFAULT_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf"
DEFAULT_TEST_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf_test"
DEFAULT_API_BASE_URL = "http://localhost:8000/api/v1"
DEFAULT_REPLY_PROVIDER = "openai"
DEFAULT_REPLY_MODEL = "gpt-4o-mini"
DEFAULT_REPLY_TEMPERATURE = 0.2
DEFAULT_REPLY_MAX_OUTPUT_TOKENS = None
DEFAULT_REPLY_MAX_CONTEXT_CHARS = 20000
DEFAULT_APPOINTMENT_DURATION_MIN = 30
DEFAULT_MESSAGE_HISTORY_SIZE = 20
DEFAULT_OPENING_TIME = "09:00"
DEFAULT_CLOSING_TIME = "17:00"
DEFAULT_TZ = ZoneInfo("Asia/Taipei")
DEFAULT_DAYS = 30
DEFAULT_SEARCH_DAYS = 7
EXPANDED_SEARCH_DAYS = 14
JSON_SENTINEL = "###JSON###"
NOT_SPECIFIED = "NOT_SPECIFIED"
GLOBAL_ERROR_THRESHOLD=3
CONSECUTIVE_ERROR_THRESHOLD=2
