"""Runtime configuration loaded from environment variables and .env."""
import sys
from typing import Any

from pydantic import Field, ValidationError, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from voice_agent.const import DEFAULT_SQLALCHEMY_DATABASE_URL, DEFAULT_TEST_SQLALCHEMY_DATABASE_URL, \
    DEFAULT_REPLY_PROVIDER, DEFAULT_REPLY_TEMPERATURE, DEFAULT_REPLY_MODEL, DEFAULT_REPLY_MAX_OUTPUT_TOKENS, \
    DEFAULT_REPLY_MAX_CONTEXT_CHARS


class Settings(BaseSettings):
    """Application settings loaded from environment variables and .env file."""

    model_config = SettingsConfigDict(
        env_prefix="",
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        env_parse_none_str="None",
    )

    # Database
    SQLALCHEMY_DATABASE_URL: str = Field(
        default=DEFAULT_SQLALCHEMY_DATABASE_URL,
        description="Async database URL (PostgreSQL/asyncpg with pgvector).",
        min_length=1,
    )
    TEST_SQLALCHEMY_DATABASE_URL: str = Field(
        default=DEFAULT_TEST_SQLALCHEMY_DATABASE_URL,
        description="Async database URL used by the test suite.",
        min_length=1,
    )

    # API keys
    OPENAI_API_KEY: str | None = Field(
        default=None,
        description="OpenAI API key for embedding, rerank, and chat calls.",
    )



    # Reply generation
    REPLY_PROVIDER: str = Field(
        default=DEFAULT_REPLY_PROVIDER,
        min_length=1,
        description="Provider for reply generation.",
    )
    REPLY_TEMPERATURE: float = Field(
        default=DEFAULT_REPLY_TEMPERATURE,
        ge=0.0,
        le=2.0,
        description="Temperature used for reply generation.",
    )
    REPLY_MODEL: str = Field(
        default=DEFAULT_REPLY_MODEL,
        min_length=1,
        description="LLM model used for replies.",
    )
    REPLY_MAX_OUTPUT_TOKENS: int | None = Field(
        default=DEFAULT_REPLY_MAX_OUTPUT_TOKENS,
        description="Optional cap on tokens generated by the reply model.",
    )
    REPLY_MAX_CONTEXT_CHARS: int = Field(
        default=DEFAULT_REPLY_MAX_CONTEXT_CHARS,
        ge=1,
        description="Maximum context characters passed into reply prompts.",
    )



    @field_validator("OPENAI_API_KEY", mode="before")
    @classmethod
    def _blank_api_key_to_none(cls, v: Any) -> str | None:
        if v is None:
            return None
        if isinstance(v, str) and not v.strip():
            return None
        return v


def load_settings_or_die() -> Settings:
    try:
        return Settings()
    except ValidationError as e:
        print("[CONFIG ERROR] Invalid environment configuration:", file=sys.stderr)
        for err in e.errors():
            loc = ".".join(str(x) for x in err.get("loc", []))
            msg = err.get("msg", "invalid value")
            print(f"  - {loc}: {msg}", file=sys.stderr)
        sys.exit(2)


settings = load_settings_or_die()
